import type { InsertChallenge } from "@shared/schema";

export const challengesSeed: InsertChallenge[] = [
  // ==================== BEGINNER (20) ====================
  {
    title: "Simple Moving Average",
    slug: "simple-moving-average",
    description: "Compute the N-day simple moving average (SMA) of a stock's closing prices. Return a Series of the same length with NaN for the first N-1 entries.\n\n**Input**: A pandas Series of daily closing prices and an integer window N.\n**Output**: A pandas Series of the rolling mean.",
    difficulty: "Beginner",
    track: "Alpha",
    points: 50,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef simple_moving_average(prices: pd.Series, window: int) -> pd.Series:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Daily Log Returns",
    slug: "daily-log-returns",
    description: "Calculate the daily logarithmic returns from a Series of prices. Log returns are defined as ln(P_t / P_{t-1}). The first entry should be NaN.\n\n**Input**: A pandas Series of daily prices.\n**Output**: A pandas Series of log returns.",
    difficulty: "Beginner",
    track: "Alpha",
    points: 50,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef log_returns(prices: pd.Series) -> pd.Series:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Portfolio Weights Normalization",
    slug: "portfolio-weights-normalization",
    description: "Given a dictionary of raw scores for each asset, normalize them so the weights sum to 1.0 and no single weight exceeds a given maximum cap. Redistribute excess weight proportionally.\n\n**Input**: A dict of asset scores and a max weight cap.\n**Output**: A dict of normalized weights.",
    difficulty: "Beginner",
    track: "Portfolio",
    points: 50,
    starterCode: "def normalize_weights(scores: dict, max_weight: float = 0.20) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Annualized Volatility",
    slug: "annualized-volatility",
    description: "Calculate the annualized volatility of a stock given its daily returns. Assume 252 trading days per year. Annualized vol = daily_std * sqrt(252).\n\n**Input**: A pandas Series of daily returns.\n**Output**: A float representing annualized volatility.",
    difficulty: "Beginner",
    track: "Risk",
    points: 50,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef annualized_volatility(daily_returns: pd.Series) -> float:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Sharpe Ratio Calculator",
    slug: "sharpe-ratio-calculator",
    description: "Compute the annualized Sharpe Ratio given a Series of daily returns and a risk-free rate. Sharpe = (mean_return - rf) / std_return * sqrt(252).\n\n**Input**: Daily returns Series and annual risk-free rate.\n**Output**: Float Sharpe Ratio.",
    difficulty: "Beginner",
    track: "Alpha",
    points: 50,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef sharpe_ratio(daily_returns: pd.Series, risk_free_rate: float = 0.02) -> float:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Maximum Drawdown",
    slug: "maximum-drawdown",
    description: "Calculate the maximum drawdown of a strategy given its cumulative return series. Max drawdown is the largest peak-to-trough decline.\n\n**Input**: A pandas Series of cumulative returns (starting at 1.0).\n**Output**: A float (negative number) representing the max drawdown.",
    difficulty: "Beginner",
    track: "Risk",
    points: 50,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef max_drawdown(cumulative_returns: pd.Series) -> float:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Exponential Moving Average",
    slug: "exponential-moving-average",
    description: "Implement an Exponential Moving Average (EMA) from scratch without using pandas ewm. Use the formula: EMA_t = alpha * price_t + (1-alpha) * EMA_{t-1}, where alpha = 2/(span+1).\n\n**Input**: A pandas Series of prices and a span.\n**Output**: A pandas Series of EMA values.",
    difficulty: "Beginner",
    track: "Alpha",
    points: 50,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef ema(prices: pd.Series, span: int) -> pd.Series:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Correlation Matrix",
    slug: "correlation-matrix",
    description: "Build a correlation matrix for a DataFrame of daily returns. Handle missing data by using pairwise complete observations.\n\n**Input**: A DataFrame where each column is an asset's daily returns.\n**Output**: A correlation matrix as a DataFrame.",
    difficulty: "Beginner",
    track: "Risk",
    points: 50,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef correlation_matrix(returns_df: pd.DataFrame) -> pd.DataFrame:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "OHLCV Bar Aggregation",
    slug: "ohlcv-bar-aggregation",
    description: "Aggregate tick-level trade data into OHLCV bars at a given time frequency. Each bar should contain open, high, low, close prices and total volume.\n\n**Input**: A DataFrame of ticks with columns [timestamp, price, volume] and a frequency string (e.g. '5T' for 5 minutes).\n**Output**: A DataFrame with OHLCV columns indexed by bar time.",
    difficulty: "Beginner",
    track: "Data",
    points: 50,
    starterCode: "import pandas as pd\n\ndef aggregate_ohlcv(ticks: pd.DataFrame, freq: str) -> pd.DataFrame:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Cumulative Returns from Daily Returns",
    slug: "cumulative-returns",
    description: "Convert a Series of daily simple returns into a cumulative return series starting at 1.0. Use the formula: cumret_t = prod(1 + r_i) for i=1..t.\n\n**Input**: A pandas Series of daily returns.\n**Output**: A pandas Series of cumulative returns.",
    difficulty: "Beginner",
    track: "Alpha",
    points: 50,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef cumulative_returns(daily_returns: pd.Series) -> pd.Series:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Trade PnL Calculator",
    slug: "trade-pnl-calculator",
    description: "Calculate the realized PnL for a list of trades. Each trade has a side ('buy'/'sell'), quantity, and price. Use FIFO matching to compute realized PnL.\n\n**Input**: A list of trade dicts with keys: side, qty, price.\n**Output**: Total realized PnL as a float.",
    difficulty: "Beginner",
    track: "Execution",
    points: 50,
    starterCode: "def calculate_pnl(trades: list) -> float:\n    # trades = [{'side': 'buy', 'qty': 100, 'price': 50.0}, ...]\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Z-Score Normalization",
    slug: "z-score-normalization",
    description: "Compute rolling Z-scores for a time series. Z-score = (value - rolling_mean) / rolling_std. This is commonly used for mean-reversion signals.\n\n**Input**: A pandas Series and a lookback window.\n**Output**: A pandas Series of Z-scores.",
    difficulty: "Beginner",
    track: "Alpha",
    points: 50,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef rolling_zscore(series: pd.Series, window: int) -> pd.Series:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Equal-Weight Portfolio Returns",
    slug: "equal-weight-portfolio",
    description: "Calculate the daily returns of an equal-weight portfolio from a DataFrame of individual asset returns. Rebalance daily.\n\n**Input**: A DataFrame of daily returns (each column is an asset).\n**Output**: A Series of daily portfolio returns.",
    difficulty: "Beginner",
    track: "Portfolio",
    points: 50,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef equal_weight_returns(returns_df: pd.DataFrame) -> pd.Series:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Bid-Ask Spread Calculator",
    slug: "bid-ask-spread",
    description: "Calculate the time-weighted average bid-ask spread from a DataFrame of quotes. Each row has bid_price, ask_price, and a timestamp. Weight by duration each quote was active.\n\n**Input**: A DataFrame with columns [timestamp, bid_price, ask_price].\n**Output**: The time-weighted average spread as a float.",
    difficulty: "Beginner",
    track: "Execution",
    points: 50,
    starterCode: "import pandas as pd\n\ndef time_weighted_spread(quotes: pd.DataFrame) -> float:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Bollinger Bands",
    slug: "bollinger-bands",
    description: "Calculate Bollinger Bands for a price series. Return the upper band, middle band (SMA), and lower band. Bands are SMA +/- k * rolling_std.\n\n**Input**: A pandas Series of prices, a window, and a multiplier k.\n**Output**: A DataFrame with columns ['upper', 'middle', 'lower'].",
    difficulty: "Beginner",
    track: "Alpha",
    points: 50,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef bollinger_bands(prices: pd.Series, window: int = 20, k: float = 2.0) -> pd.DataFrame:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Position Sizing by Volatility",
    slug: "volatility-position-sizing",
    description: "Determine position sizes for a set of assets using inverse volatility weighting. Assets with lower volatility get larger positions. Total notional should equal the target.\n\n**Input**: A dict of asset volatilities and a target notional.\n**Output**: A dict of position sizes (notional per asset).",
    difficulty: "Beginner",
    track: "Portfolio",
    points: 50,
    starterCode: "def inverse_vol_sizing(volatilities: dict, target_notional: float) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Simple Momentum Signal",
    slug: "simple-momentum-signal",
    description: "Generate a cross-sectional momentum signal: for each asset, compute the past N-day return (skipping the most recent day to avoid reversal). Rank assets and return the signal.\n\n**Input**: A DataFrame of prices (columns are assets) and lookback N.\n**Output**: A DataFrame of momentum scores, ranked 0 to 1.",
    difficulty: "Beginner",
    track: "Alpha",
    points: 50,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef momentum_signal(prices: pd.DataFrame, lookback: int = 21) -> pd.DataFrame:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Sortino Ratio",
    slug: "sortino-ratio",
    description: "Calculate the annualized Sortino Ratio. Unlike Sharpe, Sortino only penalizes downside volatility. Downside deviation uses only returns below the target return.\n\n**Input**: A pandas Series of daily returns and a target return (default 0).\n**Output**: Annualized Sortino Ratio as a float.",
    difficulty: "Beginner",
    track: "Risk",
    points: 50,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef sortino_ratio(daily_returns: pd.Series, target: float = 0.0) -> float:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Price Data Cleaning",
    slug: "price-data-cleaning",
    description: "Clean a raw price DataFrame: forward-fill missing values, remove rows where more than 50% of assets are missing, and flag days with suspicious returns (absolute return > 50%).\n\n**Input**: A DataFrame of raw prices.\n**Output**: A tuple of (cleaned DataFrame, list of flagged dates).",
    difficulty: "Beginner",
    track: "Data",
    points: 50,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef clean_prices(prices: pd.DataFrame) -> tuple:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "RSI Indicator",
    slug: "rsi-indicator",
    description: "Implement the Relative Strength Index (RSI) from scratch. RSI = 100 - (100 / (1 + RS)), where RS = avg_gain / avg_loss over the lookback period. Use Wilder's smoothing method.\n\n**Input**: A pandas Series of prices and a lookback period (default 14).\n**Output**: A pandas Series of RSI values.",
    difficulty: "Beginner",
    track: "Alpha",
    points: 50,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef rsi(prices: pd.Series, period: int = 14) -> pd.Series:\n    # Your code here\n    pass",
    testCases: [],
  },

  // ==================== PRACTITIONER (20) ====================
  {
    title: "Rolling Beta Calculation",
    slug: "rolling-beta",
    description: "Calculate the rolling 60-day beta of a stock against the SPY ETF using log returns. Beta = Cov(stock, market) / Var(market) over the rolling window.\n\n**Input**: Two pandas Series of daily log returns (stock and benchmark) and a window.\n**Output**: A pandas Series of rolling beta values.",
    difficulty: "Practitioner",
    track: "Alpha",
    points: 150,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef calculate_rolling_beta(returns: pd.Series, benchmark_returns: pd.Series, window: int = 60) -> pd.Series:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "VWAP Execution Algorithm",
    slug: "vwap-execution",
    description: "Implement a Volume Weighted Average Price (VWAP) execution algorithm. Given a historical volume profile (percent of daily volume per time bucket), create a schedule that distributes a target order across buckets to minimize tracking error vs. VWAP.\n\n**Input**: An array of volume fractions per bucket and total shares to trade.\n**Output**: An array of shares per bucket.",
    difficulty: "Practitioner",
    track: "Execution",
    points: 150,
    starterCode: "import numpy as np\n\ndef vwap_schedule(volume_profile: list, total_shares: int) -> list:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Pairs Trading Signal",
    slug: "pairs-trading-signal",
    description: "Build a pairs trading signal using cointegration. Given two stock price Series, run the Engle-Granger test, compute the spread, and generate Z-score-based entry/exit signals.\n\n**Input**: Two pandas Series of stock prices and Z-score thresholds.\n**Output**: A DataFrame with columns ['spread', 'zscore', 'signal'] where signal is 1 (long), -1 (short), or 0 (flat).",
    difficulty: "Practitioner",
    track: "Alpha",
    points: 150,
    starterCode: "import pandas as pd\nimport numpy as np\nfrom statsmodels.tsa.stattools import coint\n\ndef pairs_trading_signal(prices_a: pd.Series, prices_b: pd.Series, entry_z: float = 2.0, exit_z: float = 0.5) -> pd.DataFrame:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Value at Risk (VaR) Calculator",
    slug: "value-at-risk",
    description: "Implement three VaR methods: Historical, Parametric (Gaussian), and Cornish-Fisher (adjusted for skew/kurtosis). Return all three VaR estimates at the given confidence level.\n\n**Input**: A Series of portfolio returns and a confidence level.\n**Output**: A dict with keys 'historical', 'parametric', 'cornish_fisher'.",
    difficulty: "Practitioner",
    track: "Risk",
    points: 150,
    starterCode: "import pandas as pd\nimport numpy as np\nfrom scipy import stats\n\ndef calculate_var(returns: pd.Series, confidence: float = 0.95) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Factor Exposure Regression",
    slug: "factor-exposure-regression",
    description: "Run a cross-sectional factor regression to estimate a portfolio's exposure to Fama-French factors (Market, SMB, HML). Use OLS and return factor loadings with t-statistics.\n\n**Input**: Portfolio returns Series and a DataFrame of factor returns.\n**Output**: A dict with factor names as keys, each containing 'beta' and 't_stat'.",
    difficulty: "Practitioner",
    track: "Alpha",
    points: 150,
    starterCode: "import pandas as pd\nimport numpy as np\nfrom scipy import stats as scipy_stats\n\ndef factor_regression(portfolio_returns: pd.Series, factor_returns: pd.DataFrame) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "TWAP Execution with Random Slicing",
    slug: "twap-random-slice",
    description: "Implement a TWAP (Time-Weighted Average Price) execution algorithm with randomized child order sizes. Slice a parent order into N child orders over a time horizon, adding random noise to each slice while ensuring the total fills exactly.\n\n**Input**: Total shares, number of slices, and a randomness factor.\n**Output**: A list of child order quantities.",
    difficulty: "Practitioner",
    track: "Execution",
    points: 150,
    starterCode: "import numpy as np\n\ndef twap_random_slice(total_shares: int, num_slices: int, randomness: float = 0.2) -> list:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Covariance Matrix Shrinkage",
    slug: "covariance-shrinkage",
    description: "Implement Ledoit-Wolf covariance shrinkage from scratch. Shrink the sample covariance matrix towards a structured target (scaled identity) to improve estimation stability.\n\n**Input**: A DataFrame of asset returns.\n**Output**: A tuple of (shrunk covariance matrix as DataFrame, optimal shrinkage intensity).",
    difficulty: "Practitioner",
    track: "Risk",
    points: 150,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef ledoit_wolf_shrinkage(returns: pd.DataFrame) -> tuple:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Sector-Neutral Alpha Signal",
    slug: "sector-neutral-alpha",
    description: "Neutralize a raw alpha signal by removing sector means. For each sector, subtract the cross-sectional average signal so the signal within each sector sums to zero. This removes sector bets.\n\n**Input**: A DataFrame with columns ['ticker', 'sector', 'raw_alpha'].\n**Output**: A DataFrame with an added 'neutral_alpha' column.",
    difficulty: "Practitioner",
    track: "Alpha",
    points: 150,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef neutralize_alpha(df: pd.DataFrame) -> pd.DataFrame:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Greeks Calculator for European Options",
    slug: "options-greeks",
    description: "Implement Black-Scholes Greeks (Delta, Gamma, Theta, Vega, Rho) for European call and put options. Use the standard Black-Scholes formula.\n\n**Input**: Spot price, strike, time to expiry, risk-free rate, volatility, and option type.\n**Output**: A dict with all five Greeks.",
    difficulty: "Practitioner",
    track: "Risk",
    points: 150,
    starterCode: "import numpy as np\nfrom scipy.stats import norm\n\ndef calculate_greeks(S: float, K: float, T: float, r: float, sigma: float, option_type: str = 'call') -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Transaction Cost Model",
    slug: "transaction-cost-model",
    description: "Build a transaction cost model that estimates the cost of executing a trade. Include components for spread cost, market impact (using a square-root model), and fixed commissions.\n\n**Input**: Trade size, ADV (average daily volume), spread, volatility, and commission per share.\n**Output**: A dict with cost breakdown and total cost in basis points.",
    difficulty: "Practitioner",
    track: "Execution",
    points: 150,
    starterCode: "import numpy as np\n\ndef estimate_transaction_cost(trade_shares: int, adv: int, spread_bps: float, daily_vol: float, commission: float = 0.005) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Kalman Filter for Pairs Trading",
    slug: "kalman-filter-pairs",
    description: "Implement a Kalman Filter to dynamically estimate the hedge ratio in a pairs trade. The state is the time-varying beta between two assets. Use the filter output to generate trading signals.\n\n**Input**: Two price Series.\n**Output**: A DataFrame with columns ['hedge_ratio', 'spread', 'signal'].",
    difficulty: "Practitioner",
    track: "Alpha",
    points: 150,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef kalman_pairs(prices_a: pd.Series, prices_b: pd.Series) -> pd.DataFrame:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Risk Parity Portfolio",
    slug: "risk-parity-portfolio",
    description: "Construct a risk parity portfolio where each asset contributes equally to total portfolio risk. Use the covariance matrix and solve for weights iteratively.\n\n**Input**: A covariance matrix (DataFrame) and a target volatility.\n**Output**: A dict of asset weights.",
    difficulty: "Practitioner",
    track: "Portfolio",
    points: 150,
    starterCode: "import pandas as pd\nimport numpy as np\nfrom scipy.optimize import minimize\n\ndef risk_parity_weights(cov_matrix: pd.DataFrame, target_vol: float = 0.10) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Implied Volatility Solver",
    slug: "implied-vol-solver",
    description: "Solve for the implied volatility of a European option using Newton-Raphson method. Given the market price, find the volatility that makes the Black-Scholes price match.\n\n**Input**: Market price, spot, strike, time to expiry, risk-free rate, option type.\n**Output**: Implied volatility as a float.",
    difficulty: "Practitioner",
    track: "Risk",
    points: 150,
    starterCode: "import numpy as np\nfrom scipy.stats import norm\n\ndef implied_volatility(market_price: float, S: float, K: float, T: float, r: float, option_type: str = 'call') -> float:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Order Book Imbalance Signal",
    slug: "order-book-imbalance",
    description: "Calculate an order book imbalance signal from Level 2 market data. Compute the volume-weighted imbalance across N price levels and use it to predict short-term price direction.\n\n**Input**: A dict with 'bids' and 'asks', each a list of [price, quantity] pairs.\n**Output**: A float between -1 and 1 representing the imbalance.",
    difficulty: "Practitioner",
    track: "Execution",
    points: 150,
    starterCode: "def order_book_imbalance(order_book: dict, levels: int = 5) -> float:\n    # order_book = {'bids': [[99.5, 100], [99.4, 200]], 'asks': [[100.5, 150], ...]}\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Exponentially Weighted Covariance",
    slug: "ewm-covariance",
    description: "Compute an exponentially weighted covariance matrix with a given half-life. More recent returns should have higher weight. This is more responsive than equal-weighted covariance.\n\n**Input**: A DataFrame of returns and a half-life in days.\n**Output**: An exponentially weighted covariance matrix as a DataFrame.",
    difficulty: "Practitioner",
    track: "Risk",
    points: 150,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef ewm_covariance(returns: pd.DataFrame, halflife: int = 60) -> pd.DataFrame:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Dollar Bar Construction",
    slug: "dollar-bars",
    description: "Construct dollar bars from tick data. Instead of time-based bars, aggregate ticks until a fixed dollar threshold is reached. Each bar represents roughly equal information content.\n\n**Input**: A DataFrame of ticks [timestamp, price, volume] and a dollar threshold.\n**Output**: A DataFrame of dollar bars with OHLCV columns.",
    difficulty: "Practitioner",
    track: "Data",
    points: 150,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef construct_dollar_bars(ticks: pd.DataFrame, dollar_threshold: float) -> pd.DataFrame:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Mean-Variance Optimization",
    slug: "mean-variance-optimization",
    description: "Implement Markowitz mean-variance optimization. Find the portfolio on the efficient frontier that maximizes Sharpe Ratio, subject to fully invested and long-only constraints.\n\n**Input**: Expected returns array, covariance matrix, and risk-free rate.\n**Output**: Optimal weights as a dict.",
    difficulty: "Practitioner",
    track: "Portfolio",
    points: 150,
    starterCode: "import numpy as np\nfrom scipy.optimize import minimize\n\ndef mean_variance_optimize(expected_returns: np.ndarray, cov_matrix: np.ndarray, risk_free_rate: float = 0.02) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Turnover-Constrained Rebalance",
    slug: "turnover-constrained-rebalance",
    description: "Rebalance a portfolio to target weights while respecting a maximum turnover constraint. Minimize tracking error to target subject to the turnover budget.\n\n**Input**: Current weights dict, target weights dict, and max turnover.\n**Output**: New weights dict that respects the turnover constraint.",
    difficulty: "Practitioner",
    track: "Portfolio",
    points: 150,
    starterCode: "import numpy as np\nfrom scipy.optimize import minimize\n\ndef constrained_rebalance(current_weights: dict, target_weights: dict, max_turnover: float = 0.20) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Microstructure Noise Estimator",
    slug: "microstructure-noise",
    description: "Estimate the microstructure noise variance from high-frequency price data using the method of Zhang, Mykland, and Ait-Sahalia (2005). Separate true price variance from noise.\n\n**Input**: A numpy array of high-frequency log prices.\n**Output**: A dict with 'noise_variance', 'true_variance', and 'noise_ratio'.",
    difficulty: "Practitioner",
    track: "Data",
    points: 150,
    starterCode: "import numpy as np\n\ndef estimate_noise(log_prices: np.ndarray) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Multi-Asset Momentum Strategy",
    slug: "multi-asset-momentum",
    description: "Build a time-series momentum strategy across multiple asset classes. For each asset, go long if its past 12-month return (skipping the most recent month) is positive, otherwise go short. Apply volatility scaling.\n\n**Input**: A DataFrame of monthly prices and a vol target.\n**Output**: A DataFrame of position weights per asset per period.",
    difficulty: "Practitioner",
    track: "Alpha",
    points: 150,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef momentum_strategy(prices: pd.DataFrame, vol_target: float = 0.10) -> pd.DataFrame:\n    # Your code here\n    pass",
    testCases: [],
  },

  // ==================== EXPERT (20) ====================
  {
    title: "Portfolio Optimization with Constraints",
    slug: "portfolio-opt",
    description: "Optimize a portfolio of 50 assets to maximize Sharpe Ratio subject to: fully invested, long-only, max 5% per position, sector exposure within +/- 5% of benchmark, and turnover below 30%.\n\n**Input**: Expected returns, covariance matrix, sector assignments, benchmark weights, current weights.\n**Output**: Optimal weights dict and a metrics dict.",
    difficulty: "Expert",
    track: "Portfolio",
    points: 300,
    starterCode: "import numpy as np\nfrom scipy.optimize import minimize\n\ndef optimize_portfolio(expected_returns, cov_matrix, sectors, benchmark_weights, current_weights, constraints):\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Statistical Arbitrage Engine",
    slug: "stat-arb-engine",
    description: "Build a complete statistical arbitrage system: identify cointegrated pairs from a universe of 100 stocks, construct optimal spread portfolios, generate entry/exit signals, and track PnL with transaction costs.\n\n**Input**: A DataFrame of prices for 100 stocks and a config dict.\n**Output**: A dict with 'pairs', 'signals', 'pnl', and 'sharpe'.",
    difficulty: "Expert",
    track: "Alpha",
    points: 300,
    starterCode: "import pandas as pd\nimport numpy as np\nfrom statsmodels.tsa.stattools import coint\n\ndef stat_arb_engine(prices: pd.DataFrame, config: dict) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Monte Carlo VaR with Copulas",
    slug: "monte-carlo-var-copulas",
    description: "Implement a Monte Carlo VaR engine using Gaussian copulas to model non-linear dependence between assets. Simulate correlated returns, compute portfolio VaR and CVaR at multiple confidence levels.\n\n**Input**: Marginal distributions per asset, correlation matrix, portfolio weights, and number of simulations.\n**Output**: A dict with VaR and CVaR at 95% and 99% levels.",
    difficulty: "Expert",
    track: "Risk",
    points: 300,
    starterCode: "import numpy as np\nfrom scipy import stats\n\ndef monte_carlo_copula_var(marginals: list, correlation: np.ndarray, weights: np.ndarray, n_sims: int = 100000) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Optimal Execution with Almgren-Chriss",
    slug: "almgren-chriss-execution",
    description: "Implement the Almgren-Chriss optimal execution model. Find the optimal trading trajectory that minimizes expected cost + risk aversion * variance of cost. Handle both permanent and temporary market impact.\n\n**Input**: Total shares, time horizon, risk aversion, volatility, permanent/temporary impact coefficients.\n**Output**: Optimal trajectory as a list and expected cost.",
    difficulty: "Expert",
    track: "Execution",
    points: 300,
    starterCode: "import numpy as np\n\ndef almgren_chriss(total_shares: int, T: int, risk_aversion: float, sigma: float, eta: float, gamma: float) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Hidden Markov Model Regime Detection",
    slug: "hmm-regime-detection",
    description: "Fit a Hidden Markov Model to market returns to detect bull/bear/crisis regimes. Use the Baum-Welch algorithm for training and Viterbi algorithm for decoding. Estimate regime-conditional parameters.\n\n**Input**: A Series of daily returns and number of regimes.\n**Output**: A dict with 'regimes', 'transition_matrix', 'regime_means', 'regime_vols'.",
    difficulty: "Expert",
    track: "Alpha",
    points: 300,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef fit_hmm(returns: pd.Series, n_regimes: int = 3) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Cross-Sectional Alpha Model with IC Analysis",
    slug: "cross-sectional-alpha-ic",
    description: "Build a multi-factor alpha model that combines multiple signals using IC-weighted averaging. Implement information coefficient analysis, turnover decay, and out-of-sample IC prediction.\n\n**Input**: A dict of factor DataFrames and forward returns DataFrame.\n**Output**: A dict with combined alpha, IC per factor, and IC decay curves.",
    difficulty: "Expert",
    track: "Alpha",
    points: 300,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef build_alpha_model(factors: dict, forward_returns: pd.DataFrame) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Volatility Surface Calibration",
    slug: "vol-surface-calibration",
    description: "Calibrate a volatility surface from market option prices. Fit the SABR model to each expiry slice, interpolate across strikes and expiries, and ensure no-arbitrage conditions (no butterfly or calendar spread arbitrage).\n\n**Input**: A DataFrame of option market data [strike, expiry, price, type] and forward prices.\n**Output**: A callable vol surface function and calibrated SABR parameters.",
    difficulty: "Expert",
    track: "Risk",
    points: 300,
    starterCode: "import numpy as np\nfrom scipy.optimize import minimize\n\ndef calibrate_vol_surface(market_data: list, forwards: dict) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Hierarchical Risk Parity (HRP)",
    slug: "hierarchical-risk-parity",
    description: "Implement the Hierarchical Risk Parity algorithm by Lopez de Prado. Use hierarchical clustering on the correlation matrix, quasi-diagonalize, and recursively bisect to allocate risk. Compare performance against traditional MVO.\n\n**Input**: A DataFrame of returns.\n**Output**: HRP weights dict and comparison metrics vs. equal-weight and MVO.",
    difficulty: "Expert",
    track: "Portfolio",
    points: 300,
    starterCode: "import pandas as pd\nimport numpy as np\nfrom scipy.cluster.hierarchy import linkage, fcluster\nfrom scipy.spatial.distance import squareform\n\ndef hierarchical_risk_parity(returns: pd.DataFrame) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Market Making Simulator",
    slug: "market-making-simulator",
    description: "Build a market making engine that posts two-sided quotes. Implement inventory-aware pricing (Avellaneda-Stoikov model), handle adverse selection, and manage position limits. Track PnL, inventory, and fill rates.\n\n**Input**: A sequence of market events and model parameters.\n**Output**: A dict with pnl_curve, inventory_curve, fill_rate, and sharpe.",
    difficulty: "Expert",
    track: "Execution",
    points: 300,
    starterCode: "import numpy as np\n\ndef market_maker(events: list, params: dict) -> dict:\n    # events = [{'type': 'trade', 'price': 100, 'size': 10, 'side': 'buy'}, ...]\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "GARCH Volatility Forecasting",
    slug: "garch-volatility-forecast",
    description: "Implement a GARCH(1,1) model from scratch using maximum likelihood estimation. Forecast multi-step-ahead volatility and compare against realized volatility. Include diagnostic tests (Ljung-Box on standardized residuals).\n\n**Input**: A Series of returns and forecast horizon.\n**Output**: A dict with 'params', 'conditional_vol', 'forecast', and 'diagnostics'.",
    difficulty: "Expert",
    track: "Risk",
    points: 300,
    starterCode: "import pandas as pd\nimport numpy as np\nfrom scipy.optimize import minimize\n\ndef garch_forecast(returns: pd.Series, horizon: int = 10) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Neural Network Alpha Signal",
    slug: "nn-alpha-signal",
    description: "Build a neural network that predicts next-day stock returns from technical features. Use walk-forward optimization with expanding windows, implement proper cross-validation (no look-ahead bias), and evaluate with IC and long-short returns.\n\n**Input**: A DataFrame of features and a target returns Series.\n**Output**: A dict with predictions, IC time series, and cumulative long-short returns.",
    difficulty: "Expert",
    track: "Alpha",
    points: 300,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef nn_alpha_model(features: pd.DataFrame, target: pd.Series, config: dict) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Credit Risk Model (Merton's Framework)",
    slug: "merton-credit-risk",
    description: "Implement Merton's structural credit risk model. Given a firm's equity value and volatility, infer asset value and asset volatility by solving the system of equations. Calculate probability of default and credit spread.\n\n**Input**: Equity value, equity vol, debt face value, risk-free rate, time to maturity.\n**Output**: A dict with 'asset_value', 'asset_vol', 'default_prob', 'credit_spread'.",
    difficulty: "Expert",
    track: "Risk",
    points: 300,
    starterCode: "import numpy as np\nfrom scipy.optimize import fsolve\nfrom scipy.stats import norm\n\ndef merton_model(equity: float, equity_vol: float, debt: float, r: float, T: float) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Smart Order Router",
    slug: "smart-order-router",
    description: "Build a smart order router that optimally splits a parent order across multiple venues. Consider each venue's fee schedule, rebate structure, queue position model, and historical fill probability. Minimize total execution cost.\n\n**Input**: Order details and a list of venue specifications.\n**Output**: Allocation per venue and expected total cost.",
    difficulty: "Expert",
    track: "Execution",
    points: 300,
    starterCode: "import numpy as np\nfrom scipy.optimize import minimize\n\ndef smart_order_route(order: dict, venues: list) -> dict:\n    # order = {'side': 'buy', 'shares': 10000, 'urgency': 'medium'}\n    # venues = [{'name': 'NYSE', 'fee': 0.003, 'rebate': 0.002, 'fill_rate': 0.8}, ...]\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Robust Covariance Estimation",
    slug: "robust-covariance",
    description: "Implement multiple robust covariance estimation methods: Minimum Covariance Determinant (MCD), Gerber statistic, and de-noising via Random Matrix Theory (Marchenko-Pastur). Compare eigenvalue distributions.\n\n**Input**: A DataFrame of returns.\n**Output**: A dict with covariance matrices from each method and eigenvalue comparison.",
    difficulty: "Expert",
    track: "Risk",
    points: 300,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef robust_covariance(returns: pd.DataFrame) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Black-Litterman Model",
    slug: "black-litterman",
    description: "Implement the Black-Litterman asset allocation model end-to-end. Derive equilibrium returns from market cap weights, incorporate investor views with confidence levels, and compute posterior returns and optimal weights.\n\n**Input**: Market caps, covariance matrix, views matrix, and confidence levels.\n**Output**: A dict with 'equilibrium_returns', 'posterior_returns', 'optimal_weights'.",
    difficulty: "Expert",
    track: "Portfolio",
    points: 300,
    starterCode: "import numpy as np\n\ndef black_litterman(market_caps: np.ndarray, cov_matrix: np.ndarray, P: np.ndarray, Q: np.ndarray, omega: np.ndarray, tau: float = 0.05) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Tick Data Feature Engineering Pipeline",
    slug: "tick-feature-pipeline",
    description: "Build a feature engineering pipeline for tick data that computes: Kyle's Lambda (price impact), Amihud illiquidity ratio, realized volatility (multiple estimators), VPIN (Volume-synchronized PIN), and order flow toxicity metrics.\n\n**Input**: A DataFrame of tick data [timestamp, price, volume, side].\n**Output**: A DataFrame of computed features at a configurable sampling frequency.",
    difficulty: "Expert",
    track: "Data",
    points: 300,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef tick_feature_pipeline(ticks: pd.DataFrame, sample_freq: str = '5T') -> pd.DataFrame:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Reinforcement Learning Portfolio Manager",
    slug: "rl-portfolio-manager",
    description: "Implement a Deep Q-Network (DQN) agent that learns to manage a portfolio of 10 assets. The state includes returns, volatility, and current positions. Actions are discrete rebalancing decisions. Optimize for risk-adjusted returns net of costs.\n\n**Input**: A DataFrame of historical returns and environment config.\n**Output**: A dict with 'policy_weights', 'backtest_returns', 'sharpe', and 'training_curve'.",
    difficulty: "Expert",
    track: "Alpha",
    points: 300,
    starterCode: "import numpy as np\nimport pandas as pd\n\ndef rl_portfolio_manager(returns: pd.DataFrame, config: dict) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Expected Shortfall Backtesting",
    slug: "es-backtesting",
    description: "Implement a complete Expected Shortfall (CVaR) backtesting framework. Include multiple ES estimation methods, traffic light tests (Basel framework), and dynamic calibration. Handle the challenges of ES backtesting vs. VaR backtesting.\n\n**Input**: Portfolio returns, ES model estimates, and confidence level.\n**Output**: A dict with test results, violations, and regulatory classification.",
    difficulty: "Expert",
    track: "Risk",
    points: 300,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef backtest_expected_shortfall(returns: pd.Series, es_estimates: pd.Series, confidence: float = 0.975) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Latency Arbitrage Detector",
    slug: "latency-arb-detector",
    description: "Build a system to detect latency arbitrage in cross-listed securities. Compare timestamps and prices across venues, identify stale quotes, and estimate the information advantage. Model the adverse selection cost to liquidity providers.\n\n**Input**: Two DataFrames of quotes from different venues.\n**Output**: A dict with 'arb_opportunities', 'avg_duration_ms', 'total_profit', and 'adverse_selection_cost'.",
    difficulty: "Expert",
    track: "Execution",
    points: 300,
    starterCode: "import pandas as pd\nimport numpy as np\n\ndef detect_latency_arb(venue_a_quotes: pd.DataFrame, venue_b_quotes: pd.DataFrame) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
  {
    title: "Multi-Period Portfolio Optimization",
    slug: "multi-period-portfolio-opt",
    description: "Implement multi-period portfolio optimization using dynamic programming. Account for transaction costs, return predictability decay, and changing risk forecasts across the investment horizon. Compare against single-period myopic rebalancing.\n\n**Input**: Return forecasts over T periods, cost structure, and risk model.\n**Output**: Optimal trajectory of weights and comparison with myopic approach.",
    difficulty: "Expert",
    track: "Portfolio",
    points: 300,
    starterCode: "import numpy as np\n\ndef multi_period_optimize(return_forecasts: list, cov_matrices: list, costs: dict, T: int) -> dict:\n    # Your code here\n    pass",
    testCases: [],
  },
];
